version: "3.7"

services:
  oltp:
    image: postgres:16.1
    environment:
      POSTGRES_DB: 'sales_oltp'
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d sales_oltp"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  generator:
    build:
      context: .
      dockerfile: ./generator/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./shared:/shared
    depends_on:
      oltp:
        condition: service_healthy
  dagster-dbt:
    build:
      context: .
      dockerfile: ./dagster-dbt/Dockerfile
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        DAGSTER_HOME: /dagster-dbt/postcard_company_dm
    volumes:
        - ./shared:/shared
        - ./dagster-dbt/postcard_company_dm:/dagster-dbt/postcard_company_dm
    ports:
        - "3000:3000"
    command: dagit -h 0.0.0.0
    depends_on:
      generator:
        condition: service_completed_successfully
  superset:
    build:
      context: .
      dockerfile: ./superset/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        SUPERSET_ADMIN: $SUPERSET_ADMIN
        SUPERSET_PASSWORD: $SUPERSET_PASSWORD
    ports:
        - "8088:8088"
    command:     gunicorn --bind  "0.0.0.0:8088" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
    volumes:
        - ./shared/db:/app/superset_home/db
    depends_on:
      - dagster-dbt
